config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    member do
      post :join
      post :quit
    end
    collection do
      get :search
    end
    resources :posts
  end

  namespace :account do
    resources :groups
    resources :posts
  end
  # root 'welcome#index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :posts
  validates :title, presence: true

  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user

  mount_uploader :image, ImageUploader
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts

  has_many :group_relationships
  has_many :participated_groups, :through => :group_relationships, :source => :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = current_user.posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :validate_search_key, only: [:search]
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end
  # 实作看板的“新增” new / create
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new
    end
  end
  # 实作看板的“编辑” edit / update
  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: "Group deleted"
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "加入本讨论成功！"
    else
      flash[:warning] = "你已经是本讨论版成员了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出本讨论版！"
    else
      flash[:warning] = "你不是本讨论版成员，怎么退出 XD"
    end

    redirect_to group_path(@group)
  end

  def search
    if @query_string.present?
      search_result = Group.ransack(@search_criteria).result(:distinct => true)
      @groups = search_result.paginate(:page => params[:page], :per_page => 5 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { :title_cont => query_string }
  end

  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])

    if current_user != @group.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def group_params
    params.require(:group).permit(:title, :description, :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
  end

  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to account_posts_path, notice: 'Post Update Success!'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @post = Post.find([:id])
    @post.destroy
    redirect_to account_posts_path, alert: 'Post deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # flash[:alert] = "早安！你好！"
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_highlight_content(group,query_string)
    excerpt_cont = excerpt(group.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                   data-target=".navbar-ex1-collapse">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <div class="navbar-collapse navbar-ex1-collapse collapse"  aria-expanded="false">
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to("Groups", groups_path) %>
              </li>
            </ul>
            <div class="nav navbar-nav navbar-left">
              <%= form_tag search_groups_path, :method => :get do %>
                <div class="input-group" id="search-id" >
                  <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入搜索内容...">
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                  </div>
                </div>
              <% end %>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %></li>
                  <li><%= link_to("登陆", new_user_session_path) %></li>
                <% else %>
                  <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to("My Groups", account_groups_path) %></li>
                      <li><%= link_to("My Posts", account_posts_path) %></li>
                      <li class="divider"> </li>
                      <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>

    </div>
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑讨论版</h2>
  <hr>

  <% if @group.image.present? %>
    <span>目前图片</span>
    <br>
    <%= image_tag(@group.image.thumb.url) %>
  <% end %>

  <%= render "form"%>
  <!-- <%= form_for @group do |f| %>

  <% if @group.errors.any? %>
    <ul>
      <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  标题
  <br>
  <%= f.text_field :title %>
  <br>
  叙述
  <br>
  <%= f.text_area :description %>
  <br>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
  <% end %> -->
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td width="150">Movie Pic</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.id %></td>
          <td>
            <%= link_to group_path(group) do %>
              <% if group.image.present? %>
                <%= image_tag(group.image.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", calss: "thumbnail") %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td><%= group.user.email %></td>
          <td>
            <% if current_user && current_user == group.user %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增讨论版</h2>

    <hr>
    <%= render "form"%>
    <!-- <%= form_for @group do |f| %>

    <% if @group.errors.any? %>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    标题
    <br>
    <%= f.text_field :title %>
    <br>
    叙述
    <br>
    <%= f.text_area :description %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %> -->

</div>

app/views/groups/search.html.erb
<div>
  <br>
  <% if @query_string.blank? %>
    <div class="search-info-title">
      Sorry, The search content cannot be blank, please type some product into to search.
    </div>
    <% elsif @groups.blank? %>
    <br>
    <h2 class="search-info-title">搜索内容不能为空，请输入关键字搜索...</h2>
  <% else %>
    <h2 class="search-info-title">有关"<%= @query_string %>"的信息</h2>
    <div class="search-result">
      <div class="row groups-show0"></div>
      <div class="group-table">
        <% @groups.each do |group| %>
          <div class:"row groups-show">
            <div class="col-md-12 col-lg-9 col-lg-offset-1">
              <div class="pull-right">
                发布时间: <%= group.created_at.to_date %>
              </div>
              <p><%= link_to(render_highlight_content(group, @query_string), group_path(group)) %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class:"text-center">
      <%= will_paginate(@groups, renderer: BootstrapPagination::Rails) %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@group) %>
        <label class="label label-success">群组成员</label>
          <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning">不是群组成员</label>
          <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>

    <%= link_to("Write a Posts", new_group_post_path(@group), class: "btn btn-default pull-right")%>

  </div>
  
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>文章内容</th>
        <th>发表者</th>
        <th>发表时间</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td><%= post.user.email %></td>
          <td><%= post.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @posts%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails115</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for [@group, @post] do |f| %>

<div class="form-post">
  <%= f.input :content, input_html: {class: "form-control"} %>
</div>
<%= f.submit "Submit", class:"btn btn-primary", data: {disable_with: "Submitting..."} %>
<% end %>

app/views/posts/edit.html.erb
<h2 class="text-center">编辑文章</h2>
<hr>
<div class="col-md-4 col-md-offset-4">
  <%= render "form"%>
</div>

app/views/posts/new.html.erb
<h2 class="text-center">新增文章</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>